/*
 * Matches lines like:
 * // ...
 * # ...
 * <!-- ...
 * ; ...
 * " ...
 * ' ...
 * {/* ...
 * /* ...
 */
const TRUNCATION_REGEX = /^\s*(\/\/|#|<!--|;|"|'|\{\/\*|\/\*)\s*\.{3,}.*\s*$/

export const is_truncation_line = (line: string) => TRUNCATION_REGEX.test(line)
