export const CHECKPOINT_DEFAULT_LIFESPAN = 24
export const DEFAULT_CONTEXT_SIZE_WARNING_THRESHOLD = 60000
export const MAX_FILE_TOKENS_FOR_COMMIT_MESSAGE = 20000
export const MAX_PROMPT_CHARS_IN_COMMIT_MESSAGE = 1000
export const GIT_LOG_SINCE_DURATION = '6 months ago'
